import { connectDatabase, disconnectDatabase } from '../config/db';
import { logger } from '../config/logger';
import { BranchModel, CategoryModel, ManufacturerModel, MedicineModel, InventoryModel } from '../models';

/**
 * Populates a handful of realistic medicines (with stock) on top of the base
 * `seed.ts` data — purely so a fresh local environment has something to look
 * at in the storefront/dashboard. Not required for the app to function;
 * run `npm run seed` first.
 */
async function main(): Promise<void> {
  await connectDatabase();

  const branch = await BranchModel.findOne({ code: 'MAIN' });
  const otc = await CategoryModel.findOne({ slug: 'over-the-counter' });
  const rx = await CategoryModel.findOne({ slug: 'prescription-medicines' });
  const devices = await CategoryModel.findOne({ slug: 'healthcare-devices' });
  const babyCare = await CategoryModel.findOne({ slug: 'baby-care' });
  const personalCare = await CategoryModel.findOne({ slug: 'personal-care' });
  const cipla = await ManufacturerModel.findOne({ slug: 'cipla' });
  const sun = await ManufacturerModel.findOne({ slug: 'sun-pharma' });
  const drReddys = await ManufacturerModel.findOne({ slug: 'dr-reddys' });
  const jnj = await ManufacturerModel.findOne({ slug: 'johnson-johnson' });
  const mankind = await ManufacturerModel.findOne({ slug: 'mankind-pharma' });
  const lupin = await ManufacturerModel.findOne({ slug: 'lupin' });
  const abbott = await ManufacturerModel.findOne({ slug: 'abbott-india' });
  const gsk = await ManufacturerModel.findOne({ slug: 'gsk-pharma' });
  const glenmark = await ManufacturerModel.findOne({ slug: 'glenmark' });
  const torrent = await ManufacturerModel.findOne({ slug: 'torrent-pharma' });
  const himalaya = await ManufacturerModel.findOne({ slug: 'himalaya-wellness' });
  const reckitt = await ManufacturerModel.findOne({ slug: 'reckitt-benckiser' });
  const zydus = await ManufacturerModel.findOne({ slug: 'zydus-cadila' });
  const alkem = await ManufacturerModel.findOne({ slug: 'alkem-labs' });

  if (
    !branch || !otc || !rx || !devices || !babyCare || !personalCare ||
    !cipla || !sun || !drReddys || !jnj || !mankind || !lupin || !abbott ||
    !gsk || !glenmark || !torrent || !himalaya || !reckitt || !zydus || !alkem
  ) {
    throw new Error('Run `npm run seed` first to create the branch/categories/manufacturers.');
  }

  // Verified-working, generic (no third-party branding) stock photos, reused across products of
  // the same form factor — a real catalog would have per-SKU photography, but a launch-ready demo
  // just needs every product to render a real image instead of a broken link.
  const IMG_TABLETS_1 = 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600';
  const IMG_TABLETS_2 = 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=600';
  const IMG_TABLETS_3 = 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=600';
  const IMG_BLISTER = 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=600';
  const IMG_CAPSULES_1 = 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600';
  const IMG_CAPSULES_2 = 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=600';
  const IMG_CREAM = 'https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?w=600';
  const IMG_DEVICE = 'https://images.unsplash.com/photo-1615486511484-92e172cc4fe0?w=600';
  const IMG_VIALS = 'https://images.unsplash.com/photo-1576671081837-49000212a370?w=600';
  const IMG_PERSONAL = 'https://images.unsplash.com/photo-1583947581924-860bda6a26df?w=600';

  const medicines = [
    {
      name: 'Paracetamol 650mg Tablet',
      slug: 'paracetamol-650mg-tablet',
      shortDescription: 'Fast relief from fever and mild to moderate pain',
      description:
        'Paracetamol 650mg is used for the treatment of fever and mild to moderate pain including headache, body ache, and toothache.',
      composition: ['Paracetamol 650mg'],
      uses: ['Fever', 'Headache', 'Body ache', 'Toothache'],
      dosage: 'One tablet every 4-6 hours as needed, not exceeding 4 tablets in 24 hours.',
      sideEffects: ['Nausea', 'Rash (rare)'],
      storageInstructions: 'Store below 30°C in a dry place, away from sunlight.',
      manufacturerId: cipla._id,
      categoryId: otc._id,
      categoryGroup: 'medicine',
      medicineType: 'tablet',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 35,
      sellingPrice: 28,
      gstPercentage: 12,
      hsnCode: '30049099',
      packSize: '15 tablets',
      images: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600'],
      tags: ['fever', 'pain relief', 'paracetamol'],
      isActive: true,
      stock: 500,
    },
    {
      name: 'Vitamin C 500mg Tablet',
      slug: 'vitamin-c-500mg-tablet',
      shortDescription: 'Immunity booster with antioxidant properties',
      description: 'Vitamin C supplement that supports immune function, skin health, and acts as an antioxidant.',
      composition: ['Ascorbic Acid 500mg'],
      uses: ['Immunity support', 'Antioxidant', 'Skin health'],
      dosage: 'One tablet daily after meals.',
      sideEffects: ['Mild stomach upset at high doses'],
      storageInstructions: 'Store in a cool, dry place.',
      manufacturerId: sun._id,
      categoryId: otc._id,
      categoryGroup: 'healthcare',
      medicineType: 'tablet',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 120,
      sellingPrice: 89,
      gstPercentage: 12,
      hsnCode: '30045090',
      packSize: '30 tablets',
      images: ['https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=600'],
      tags: ['vitamin', 'immunity'],
      isActive: true,
      stock: 300,
    },
    {
      name: 'Amoxicillin 500mg Capsule',
      slug: 'amoxicillin-500mg-capsule',
      shortDescription: 'Broad-spectrum antibiotic for bacterial infections',
      description: 'Amoxicillin is a penicillin antibiotic used to treat a wide variety of bacterial infections.',
      composition: ['Amoxicillin 500mg'],
      uses: ['Bacterial infections', 'Respiratory tract infections'],
      dosage: 'As prescribed by your doctor, typically every 8 hours.',
      sideEffects: ['Diarrhea', 'Nausea', 'Allergic reactions'],
      storageInstructions: 'Store below 25°C, protect from moisture.',
      manufacturerId: cipla._id,
      categoryId: rx._id,
      categoryGroup: 'medicine',
      medicineType: 'capsule',
      scheduleClass: 'schedule_h',
      prescriptionRequired: true,
      mrp: 95,
      sellingPrice: 78,
      gstPercentage: 12,
      hsnCode: '30041020',
      packSize: '10 capsules',
      images: ['https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600'],
      tags: ['antibiotic'],
      isActive: true,
      stock: 150,
    },
    {
      name: 'Digital Infrared Thermometer',
      slug: 'digital-infrared-thermometer',
      shortDescription: 'Non-contact infrared thermometer for accurate readings',
      description:
        'A non-contact infrared thermometer for quick and accurate body temperature measurement, suitable for all ages.',
      composition: ['N/A'],
      uses: ['Body temperature measurement'],
      sideEffects: [],
      storageInstructions: 'Store in the provided case, away from direct sunlight.',
      manufacturerId: sun._id,
      categoryId: devices._id,
      categoryGroup: 'devices',
      medicineType: 'device',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 1499,
      sellingPrice: 999,
      gstPercentage: 18,
      hsnCode: '90258090',
      packSize: '1 unit',
      images: ['https://images.unsplash.com/photo-1615486511484-92e172cc4fe0?w=600'],
      tags: ['thermometer', 'device'],
      isActive: true,
      stock: 80,
    },
    {
      name: 'Cough Syrup (Honey & Tulsi)',
      slug: 'cough-syrup-honey-tulsi',
      shortDescription: 'Ayurvedic relief from cough and throat irritation',
      description: 'A soothing herbal cough syrup with honey and tulsi extracts for relief from cough and throat irritation.',
      composition: ['Honey', 'Tulsi Extract', 'Ginger Extract'],
      uses: ['Cough relief', 'Sore throat'],
      dosage: 'Two teaspoons, 3 times a day.',
      sideEffects: [],
      storageInstructions: 'Store in a cool place, shake well before use.',
      manufacturerId: cipla._id,
      categoryId: otc._id,
      categoryGroup: 'medicine',
      medicineType: 'syrup',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 110,
      sellingPrice: 85,
      gstPercentage: 12,
      hsnCode: '30049011',
      packSize: '100ml',
      images: ['https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=600'],
      tags: ['cough', 'cold', 'ayurvedic'],
      isActive: true,
      stock: 200,
    },
    {
      name: 'Baby Diaper Rash Cream',
      slug: 'baby-diaper-rash-cream',
      shortDescription: 'Gentle protective cream for diaper rash',
      description: 'A gentle, dermatologically tested cream that protects baby skin from diaper rash and soothes irritation.',
      composition: ['Zinc Oxide 15%'],
      uses: ['Diaper rash prevention', 'Skin protection'],
      dosage: 'Apply a thin layer at every diaper change.',
      sideEffects: [],
      storageInstructions: 'Store below 30°C.',
      manufacturerId: sun._id,
      categoryId: otc._id,
      categoryGroup: 'baby_care',
      medicineType: 'ointment',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 199,
      sellingPrice: 159,
      gstPercentage: 18,
      hsnCode: '33049910',
      packSize: '50g',
      images: ['https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?w=600'],
      tags: ['baby care', 'skin'],
      isActive: true,
      stock: 120,
    },

    // ---- Pain & Fever ----
    {
      name: 'Paracetamol 500mg Tablet',
      slug: 'paracetamol-500mg-tablet',
      shortDescription: 'Everyday relief from fever and mild pain',
      description: 'Paracetamol 500mg is a widely used antipyretic and analgesic for fever, headache, and minor aches.',
      composition: ['Paracetamol 500mg'],
      uses: ['Fever', 'Headache', 'Mild pain'],
      dosage: 'One or two tablets every 4-6 hours as needed, not exceeding 8 tablets in 24 hours.',
      sideEffects: ['Nausea (rare)'],
      storageInstructions: 'Store below 30°C in a dry place.',
      manufacturerId: gsk._id,
      categoryId: otc._id,
      categoryGroup: 'medicine',
      medicineType: 'tablet',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 22,
      sellingPrice: 18,
      gstPercentage: 12,
      hsnCode: '30049099',
      packSize: '10 tablets',
      images: [IMG_TABLETS_1],
      tags: ['fever', 'pain relief'],
      isActive: true,
      stock: 600,
    },
    {
      name: 'Ibuprofen 400mg Tablet',
      slug: 'ibuprofen-400mg-tablet',
      shortDescription: 'Anti-inflammatory relief for pain and swelling',
      description: 'Ibuprofen 400mg is an NSAID used for pain, inflammation, and fever relief.',
      composition: ['Ibuprofen 400mg'],
      uses: ['Pain relief', 'Inflammation', 'Fever'],
      dosage: 'One tablet every 6-8 hours after food, not exceeding 3 tablets a day.',
      sideEffects: ['Stomach upset', 'Heartburn'],
      storageInstructions: 'Store below 30°C, away from moisture.',
      manufacturerId: cipla._id,
      categoryId: otc._id,
      categoryGroup: 'medicine',
      medicineType: 'tablet',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 38,
      sellingPrice: 30,
      gstPercentage: 12,
      hsnCode: '30049099',
      packSize: '15 tablets',
      images: [IMG_TABLETS_2],
      tags: ['pain relief', 'inflammation'],
      isActive: true,
      stock: 400,
    },
    {
      name: 'Diclofenac 50mg Tablet',
      slug: 'diclofenac-50mg-tablet',
      shortDescription: 'Fast-acting relief for joint and muscle pain',
      description: 'Diclofenac 50mg is an NSAID commonly prescribed for arthritis, back pain, and post-injury inflammation.',
      composition: ['Diclofenac Sodium 50mg'],
      uses: ['Joint pain', 'Muscle pain', 'Arthritis'],
      dosage: 'As prescribed, typically one tablet twice daily after food.',
      sideEffects: ['Stomach irritation', 'Dizziness'],
      storageInstructions: 'Store below 25°C.',
      manufacturerId: lupin._id,
      categoryId: rx._id,
      categoryGroup: 'medicine',
      medicineType: 'tablet',
      scheduleClass: 'schedule_h',
      prescriptionRequired: true,
      mrp: 45,
      sellingPrice: 36,
      gstPercentage: 12,
      hsnCode: '30049069',
      packSize: '10 tablets',
      images: [IMG_TABLETS_3],
      tags: ['pain relief', 'arthritis'],
      isActive: true,
      stock: 250,
    },
    {
      name: 'Aspirin 75mg Tablet',
      slug: 'aspirin-75mg-tablet',
      shortDescription: 'Low-dose aspirin for cardiac protection',
      description: 'Aspirin 75mg low-dose tablet, commonly prescribed for cardiovascular protection under medical supervision.',
      composition: ['Aspirin 75mg'],
      uses: ['Cardiovascular protection', 'Blood thinning'],
      dosage: 'One tablet daily as prescribed by your doctor.',
      sideEffects: ['Stomach irritation', 'Bleeding risk'],
      storageInstructions: 'Store below 25°C in a dry place.',
      manufacturerId: zydus._id,
      categoryId: rx._id,
      categoryGroup: 'medicine',
      medicineType: 'tablet',
      scheduleClass: 'schedule_h',
      prescriptionRequired: true,
      mrp: 18,
      sellingPrice: 14,
      gstPercentage: 12,
      hsnCode: '30049099',
      packSize: '14 tablets',
      images: [IMG_BLISTER],
      tags: ['cardiac', 'blood thinner'],
      isActive: true,
      stock: 300,
    },

    // ---- Antibiotics (Rx) ----
    {
      name: 'Azithromycin 500mg Tablet',
      slug: 'azithromycin-500mg-tablet',
      shortDescription: 'Broad-spectrum antibiotic, 3-day course',
      description: 'Azithromycin 500mg is a macrolide antibiotic used to treat respiratory, ear, and skin infections.',
      composition: ['Azithromycin 500mg'],
      uses: ['Respiratory infections', 'Skin infections', 'Throat infections'],
      dosage: 'One tablet daily for 3 days, or as prescribed.',
      sideEffects: ['Nausea', 'Diarrhea', 'Abdominal pain'],
      storageInstructions: 'Store below 30°C, protect from light.',
      manufacturerId: cipla._id,
      categoryId: rx._id,
      categoryGroup: 'medicine',
      medicineType: 'tablet',
      scheduleClass: 'schedule_h',
      prescriptionRequired: true,
      mrp: 120,
      sellingPrice: 98,
      gstPercentage: 12,
      hsnCode: '30041020',
      packSize: '3 tablets',
      images: [IMG_TABLETS_1],
      tags: ['antibiotic'],
      isActive: true,
      stock: 200,
    },
    {
      name: 'Ciprofloxacin 500mg Tablet',
      slug: 'ciprofloxacin-500mg-tablet',
      shortDescription: 'Fluoroquinolone antibiotic for bacterial infections',
      description: 'Ciprofloxacin 500mg is used to treat urinary tract, respiratory, and gastrointestinal bacterial infections.',
      composition: ['Ciprofloxacin 500mg'],
      uses: ['Urinary tract infections', 'Bacterial infections'],
      dosage: 'One tablet twice daily as prescribed.',
      sideEffects: ['Nausea', 'Tendon pain (rare)'],
      storageInstructions: 'Store below 25°C, away from sunlight.',
      manufacturerId: torrent._id,
      categoryId: rx._id,
      categoryGroup: 'medicine',
      medicineType: 'tablet',
      scheduleClass: 'schedule_h',
      prescriptionRequired: true,
      mrp: 85,
      sellingPrice: 68,
      gstPercentage: 12,
      hsnCode: '30041020',
      packSize: '10 tablets',
      images: [IMG_TABLETS_2],
      tags: ['antibiotic', 'uti'],
      isActive: true,
      stock: 180,
    },
    {
      name: 'Doxycycline 100mg Capsule',
      slug: 'doxycycline-100mg-capsule',
      shortDescription: 'Tetracycline antibiotic for infections and acne',
      description: 'Doxycycline 100mg is a broad-spectrum antibiotic used for respiratory infections, acne, and tick-borne illnesses.',
      composition: ['Doxycycline 100mg'],
      uses: ['Bacterial infections', 'Acne', 'Respiratory infections'],
      dosage: 'One capsule twice daily as prescribed.',
      sideEffects: ['Photosensitivity', 'Nausea'],
      storageInstructions: 'Store below 25°C, protect from light and moisture.',
      manufacturerId: alkem._id,
      categoryId: rx._id,
      categoryGroup: 'medicine',
      medicineType: 'capsule',
      scheduleClass: 'schedule_h',
      prescriptionRequired: true,
      mrp: 65,
      sellingPrice: 52,
      gstPercentage: 12,
      hsnCode: '30041010',
      packSize: '10 capsules',
      images: [IMG_CAPSULES_1],
      tags: ['antibiotic', 'acne'],
      isActive: true,
      stock: 150,
    },
    {
      name: 'Cefixime 200mg Tablet',
      slug: 'cefixime-200mg-tablet',
      shortDescription: 'Third-generation cephalosporin antibiotic',
      description: 'Cefixime 200mg is used to treat a wide range of bacterial infections including UTIs and throat infections.',
      composition: ['Cefixime 200mg'],
      uses: ['Bacterial infections', 'UTI', 'Throat infections'],
      dosage: 'One tablet twice daily as prescribed.',
      sideEffects: ['Diarrhea', 'Nausea'],
      storageInstructions: 'Store below 25°C.',
      manufacturerId: mankind._id,
      categoryId: rx._id,
      categoryGroup: 'medicine',
      medicineType: 'tablet',
      scheduleClass: 'schedule_h',
      prescriptionRequired: true,
      mrp: 110,
      sellingPrice: 89,
      gstPercentage: 12,
      hsnCode: '30041020',
      packSize: '10 tablets',
      images: [IMG_TABLETS_3],
      tags: ['antibiotic'],
      isActive: true,
      stock: 160,
    },

    // ---- Diabetes ----
    {
      name: 'Metformin 500mg Tablet',
      slug: 'metformin-500mg-tablet',
      shortDescription: 'First-line oral medication for type 2 diabetes',
      description: 'Metformin 500mg helps control blood sugar levels in people with type 2 diabetes.',
      composition: ['Metformin Hydrochloride 500mg'],
      uses: ['Type 2 diabetes management'],
      dosage: 'One tablet with meals, twice daily, or as prescribed.',
      sideEffects: ['Stomach upset', 'Diarrhea'],
      storageInstructions: 'Store below 30°C in a dry place.',
      manufacturerId: mankind._id,
      categoryId: rx._id,
      categoryGroup: 'medicine',
      medicineType: 'tablet',
      scheduleClass: 'schedule_h',
      prescriptionRequired: true,
      mrp: 55,
      sellingPrice: 42,
      gstPercentage: 12,
      hsnCode: '30049043',
      packSize: '15 tablets',
      images: [IMG_TABLETS_1],
      tags: ['diabetes'],
      isActive: true,
      stock: 350,
    },
    {
      name: 'Glimepiride 2mg Tablet',
      slug: 'glimepiride-2mg-tablet',
      shortDescription: 'Sulfonylurea for blood sugar control',
      description: 'Glimepiride 2mg stimulates insulin release to help control blood sugar in type 2 diabetes.',
      composition: ['Glimepiride 2mg'],
      uses: ['Type 2 diabetes management'],
      dosage: 'One tablet daily before breakfast, or as prescribed.',
      sideEffects: ['Low blood sugar', 'Dizziness'],
      storageInstructions: 'Store below 25°C, protect from light.',
      manufacturerId: glenmark._id,
      categoryId: rx._id,
      categoryGroup: 'medicine',
      medicineType: 'tablet',
      scheduleClass: 'schedule_h',
      prescriptionRequired: true,
      mrp: 78,
      sellingPrice: 62,
      gstPercentage: 12,
      hsnCode: '30049043',
      packSize: '15 tablets',
      images: [IMG_TABLETS_2],
      tags: ['diabetes'],
      isActive: true,
      stock: 220,
    },
    {
      name: 'Insulin Glargine Injection',
      slug: 'insulin-glargine-injection',
      shortDescription: 'Long-acting insulin for diabetes management',
      description: 'Insulin Glargine is a long-acting insulin analogue used for blood sugar control in diabetes.',
      composition: ['Insulin Glargine 100IU/ml'],
      uses: ['Type 1 and Type 2 diabetes management'],
      dosage: 'As prescribed by your doctor, typically once daily.',
      sideEffects: ['Hypoglycemia', 'Injection site reaction'],
      storageInstructions: 'Store refrigerated between 2-8°C, do not freeze.',
      manufacturerId: abbott._id,
      categoryId: rx._id,
      categoryGroup: 'medicine',
      medicineType: 'injection',
      scheduleClass: 'schedule_h',
      prescriptionRequired: true,
      mrp: 950,
      sellingPrice: 820,
      gstPercentage: 12,
      hsnCode: '30043910',
      packSize: '3ml cartridge',
      images: [IMG_VIALS],
      tags: ['diabetes', 'insulin'],
      isActive: true,
      stock: 60,
    },

    // ---- Cardiac / Blood Pressure ----
    {
      name: 'Amlodipine 5mg Tablet',
      slug: 'amlodipine-5mg-tablet',
      shortDescription: 'Calcium channel blocker for high blood pressure',
      description: 'Amlodipine 5mg is used to treat high blood pressure and chest pain (angina).',
      composition: ['Amlodipine 5mg'],
      uses: ['Hypertension', 'Angina'],
      dosage: 'One tablet daily, or as prescribed.',
      sideEffects: ['Swelling in ankles', 'Dizziness', 'Flushing'],
      storageInstructions: 'Store below 30°C.',
      manufacturerId: sun._id,
      categoryId: rx._id,
      categoryGroup: 'medicine',
      medicineType: 'tablet',
      scheduleClass: 'schedule_h',
      prescriptionRequired: true,
      mrp: 42,
      sellingPrice: 33,
      gstPercentage: 12,
      hsnCode: '30049049',
      packSize: '15 tablets',
      images: [IMG_TABLETS_3],
      tags: ['blood pressure', 'cardiac'],
      isActive: true,
      stock: 300,
    },
    {
      name: 'Atorvastatin 10mg Tablet',
      slug: 'atorvastatin-10mg-tablet',
      shortDescription: 'Statin for cholesterol management',
      description: 'Atorvastatin 10mg helps lower LDL cholesterol and reduce cardiovascular risk.',
      composition: ['Atorvastatin 10mg'],
      uses: ['High cholesterol', 'Cardiovascular risk reduction'],
      dosage: 'One tablet daily at night, or as prescribed.',
      sideEffects: ['Muscle pain', 'Liver enzyme changes'],
      storageInstructions: 'Store below 30°C, away from moisture.',
      manufacturerId: drReddys._id,
      categoryId: rx._id,
      categoryGroup: 'medicine',
      medicineType: 'tablet',
      scheduleClass: 'schedule_h',
      prescriptionRequired: true,
      mrp: 95,
      sellingPrice: 75,
      gstPercentage: 12,
      hsnCode: '30049049',
      packSize: '15 tablets',
      images: [IMG_TABLETS_1],
      tags: ['cholesterol', 'cardiac'],
      isActive: true,
      stock: 280,
    },
    {
      name: 'Telmisartan 40mg Tablet',
      slug: 'telmisartan-40mg-tablet',
      shortDescription: 'ARB for hypertension management',
      description: 'Telmisartan 40mg is an angiotensin receptor blocker used to manage high blood pressure.',
      composition: ['Telmisartan 40mg'],
      uses: ['Hypertension'],
      dosage: 'One tablet daily, or as prescribed.',
      sideEffects: ['Dizziness', 'Back pain'],
      storageInstructions: 'Store below 30°C.',
      manufacturerId: torrent._id,
      categoryId: rx._id,
      categoryGroup: 'medicine',
      medicineType: 'tablet',
      scheduleClass: 'schedule_h',
      prescriptionRequired: true,
      mrp: 88,
      sellingPrice: 70,
      gstPercentage: 12,
      hsnCode: '30049049',
      packSize: '15 tablets',
      images: [IMG_TABLETS_2],
      tags: ['blood pressure'],
      isActive: true,
      stock: 240,
    },
    {
      name: 'Clopidogrel 75mg Tablet',
      slug: 'clopidogrel-75mg-tablet',
      shortDescription: 'Antiplatelet medication for heart protection',
      description: 'Clopidogrel 75mg prevents blood clots in patients with cardiovascular disease.',
      composition: ['Clopidogrel 75mg'],
      uses: ['Cardiovascular protection', 'Stroke prevention'],
      dosage: 'One tablet daily, or as prescribed.',
      sideEffects: ['Bleeding risk', 'Bruising'],
      storageInstructions: 'Store below 25°C.',
      manufacturerId: zydus._id,
      categoryId: rx._id,
      categoryGroup: 'medicine',
      medicineType: 'tablet',
      scheduleClass: 'schedule_h',
      prescriptionRequired: true,
      mrp: 105,
      sellingPrice: 84,
      gstPercentage: 12,
      hsnCode: '30049049',
      packSize: '14 tablets',
      images: [IMG_BLISTER],
      tags: ['cardiac', 'blood thinner'],
      isActive: true,
      stock: 190,
    },

    // ---- Gastro ----
    {
      name: 'Omeprazole 20mg Capsule',
      slug: 'omeprazole-20mg-capsule',
      shortDescription: 'Proton pump inhibitor for acid reflux',
      description: 'Omeprazole 20mg reduces stomach acid production for relief from acidity, heartburn, and ulcers.',
      composition: ['Omeprazole 20mg'],
      uses: ['Acid reflux', 'Heartburn', 'Peptic ulcer'],
      dosage: 'One capsule daily before breakfast, or as prescribed.',
      sideEffects: ['Headache', 'Nausea'],
      storageInstructions: 'Store below 30°C, protect from moisture.',
      manufacturerId: sun._id,
      categoryId: otc._id,
      categoryGroup: 'medicine',
      medicineType: 'capsule',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 60,
      sellingPrice: 47,
      gstPercentage: 12,
      hsnCode: '30049099',
      packSize: '15 capsules',
      images: [IMG_CAPSULES_2],
      tags: ['acidity', 'gastro'],
      isActive: true,
      stock: 320,
    },
    {
      name: 'Pantoprazole 40mg Tablet',
      slug: 'pantoprazole-40mg-tablet',
      shortDescription: 'Effective relief from acidity and gastritis',
      description: 'Pantoprazole 40mg is a proton pump inhibitor used for acid-related stomach conditions.',
      composition: ['Pantoprazole 40mg'],
      uses: ['Acidity', 'Gastritis', 'GERD'],
      dosage: 'One tablet daily before breakfast, or as prescribed.',
      sideEffects: ['Headache', 'Diarrhea'],
      storageInstructions: 'Store below 30°C.',
      manufacturerId: alkem._id,
      categoryId: otc._id,
      categoryGroup: 'medicine',
      medicineType: 'tablet',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 65,
      sellingPrice: 51,
      gstPercentage: 12,
      hsnCode: '30049099',
      packSize: '15 tablets',
      images: [IMG_TABLETS_3],
      tags: ['acidity', 'gastro'],
      isActive: true,
      stock: 300,
    },
    {
      name: 'Domperidone 10mg Tablet',
      slug: 'domperidone-10mg-tablet',
      shortDescription: 'Relief from nausea, vomiting and bloating',
      description: 'Domperidone 10mg helps relieve nausea, vomiting, and a feeling of fullness or bloating.',
      composition: ['Domperidone 10mg'],
      uses: ['Nausea', 'Vomiting', 'Bloating'],
      dosage: 'One tablet before meals, 3 times daily, or as prescribed.',
      sideEffects: ['Dry mouth', 'Headache'],
      storageInstructions: 'Store below 30°C.',
      manufacturerId: torrent._id,
      categoryId: otc._id,
      categoryGroup: 'medicine',
      medicineType: 'tablet',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 35,
      sellingPrice: 27,
      gstPercentage: 12,
      hsnCode: '30049099',
      packSize: '10 tablets',
      images: [IMG_TABLETS_1],
      tags: ['nausea', 'gastro'],
      isActive: true,
      stock: 260,
    },
    {
      name: 'ORS Powder Sachet',
      slug: 'ors-powder-sachet',
      shortDescription: 'Oral rehydration salts for dehydration',
      description: 'Oral Rehydration Salts replenish fluids and electrolytes lost during dehydration, diarrhea, or vomiting.',
      composition: ['Sodium Chloride', 'Potassium Chloride', 'Glucose', 'Trisodium Citrate'],
      uses: ['Dehydration', 'Diarrhea recovery'],
      dosage: 'Dissolve one sachet in 200ml clean water, drink as needed.',
      sideEffects: [],
      storageInstructions: 'Store in a cool, dry place.',
      manufacturerId: gsk._id,
      categoryId: otc._id,
      categoryGroup: 'medicine',
      medicineType: 'other',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 20,
      sellingPrice: 16,
      gstPercentage: 12,
      hsnCode: '30049012',
      packSize: '21.8g sachet',
      images: [IMG_TABLETS_2],
      tags: ['rehydration', 'electrolytes'],
      isActive: true,
      stock: 500,
    },

    // ---- Allergy & Respiratory ----
    {
      name: 'Cetirizine 10mg Tablet',
      slug: 'cetirizine-10mg-tablet',
      shortDescription: 'Non-drowsy relief from allergies',
      description: 'Cetirizine 10mg provides relief from sneezing, runny nose, itching, and watery eyes caused by allergies.',
      composition: ['Cetirizine Hydrochloride 10mg'],
      uses: ['Allergic rhinitis', 'Hives', 'Itching'],
      dosage: 'One tablet daily, or as prescribed.',
      sideEffects: ['Mild drowsiness'],
      storageInstructions: 'Store below 30°C.',
      manufacturerId: gsk._id,
      categoryId: otc._id,
      categoryGroup: 'medicine',
      medicineType: 'tablet',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 30,
      sellingPrice: 23,
      gstPercentage: 12,
      hsnCode: '30049099',
      packSize: '10 tablets',
      images: [IMG_TABLETS_3],
      tags: ['allergy', 'antihistamine'],
      isActive: true,
      stock: 400,
    },
    {
      name: 'Levocetirizine 5mg Tablet',
      slug: 'levocetirizine-5mg-tablet',
      shortDescription: 'Fast relief from allergy symptoms',
      description: 'Levocetirizine 5mg is an antihistamine used for allergic rhinitis and chronic hives.',
      composition: ['Levocetirizine 5mg'],
      uses: ['Allergic rhinitis', 'Chronic hives'],
      dosage: 'One tablet daily at night, or as prescribed.',
      sideEffects: ['Drowsiness', 'Dry mouth'],
      storageInstructions: 'Store below 30°C.',
      manufacturerId: glenmark._id,
      categoryId: otc._id,
      categoryGroup: 'medicine',
      medicineType: 'tablet',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 28,
      sellingPrice: 21,
      gstPercentage: 12,
      hsnCode: '30049099',
      packSize: '10 tablets',
      images: [IMG_TABLETS_1],
      tags: ['allergy', 'antihistamine'],
      isActive: true,
      stock: 350,
    },
    {
      name: 'Montelukast 10mg Tablet',
      slug: 'montelukast-10mg-tablet',
      shortDescription: 'Preventive treatment for asthma and allergies',
      description: 'Montelukast 10mg helps prevent asthma symptoms and relieve seasonal allergy symptoms.',
      composition: ['Montelukast 10mg'],
      uses: ['Asthma prevention', 'Allergic rhinitis'],
      dosage: 'One tablet daily in the evening, or as prescribed.',
      sideEffects: ['Headache', 'Stomach pain'],
      storageInstructions: 'Store below 30°C, protect from light.',
      manufacturerId: cipla._id,
      categoryId: rx._id,
      categoryGroup: 'medicine',
      medicineType: 'tablet',
      scheduleClass: 'schedule_h',
      prescriptionRequired: true,
      mrp: 110,
      sellingPrice: 88,
      gstPercentage: 12,
      hsnCode: '30049099',
      packSize: '10 tablets',
      images: [IMG_TABLETS_2],
      tags: ['asthma', 'allergy'],
      isActive: true,
      stock: 180,
    },
    {
      name: 'Salbutamol Inhaler',
      slug: 'salbutamol-inhaler',
      shortDescription: 'Quick-relief inhaler for asthma',
      description: 'Salbutamol Inhaler provides fast relief from asthma symptoms by relaxing the airway muscles.',
      composition: ['Salbutamol 100mcg per actuation'],
      uses: ['Asthma', 'Bronchospasm relief'],
      dosage: 'One to two puffs as needed, or as prescribed.',
      sideEffects: ['Tremors', 'Rapid heartbeat'],
      storageInstructions: 'Store below 30°C, do not puncture or burn the canister.',
      manufacturerId: cipla._id,
      categoryId: rx._id,
      categoryGroup: 'medicine',
      medicineType: 'inhaler',
      scheduleClass: 'schedule_h',
      prescriptionRequired: true,
      mrp: 145,
      sellingPrice: 119,
      gstPercentage: 12,
      hsnCode: '30049014',
      packSize: '200 doses',
      images: [IMG_DEVICE],
      tags: ['asthma', 'inhaler'],
      isActive: true,
      stock: 90,
    },
    {
      name: 'Dextromethorphan Cough Syrup',
      slug: 'dextromethorphan-cough-syrup',
      shortDescription: 'Effective relief from dry cough',
      description: 'Dextromethorphan cough syrup suppresses the urge to cough for relief from dry, irritating cough.',
      composition: ['Dextromethorphan Hydrobromide 10mg/5ml'],
      uses: ['Dry cough relief'],
      dosage: 'Two teaspoons, 3 times a day, or as prescribed.',
      sideEffects: ['Drowsiness', 'Dizziness'],
      storageInstructions: 'Store below 25°C, shake well before use.',
      manufacturerId: abbott._id,
      categoryId: otc._id,
      categoryGroup: 'medicine',
      medicineType: 'syrup',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 95,
      sellingPrice: 76,
      gstPercentage: 12,
      hsnCode: '30049011',
      packSize: '100ml',
      images: [IMG_BLISTER],
      tags: ['cough', 'cold'],
      isActive: true,
      stock: 220,
    },

    // ---- Vitamins & Supplements ----
    {
      name: 'Vitamin D3 60K Sachet',
      slug: 'vitamin-d3-60k-sachet',
      shortDescription: 'Weekly Vitamin D3 supplement',
      description: 'Vitamin D3 60,000 IU sachet supports bone health and corrects Vitamin D deficiency.',
      composition: ['Cholecalciferol (Vitamin D3) 60,000 IU'],
      uses: ['Vitamin D deficiency', 'Bone health'],
      dosage: 'One sachet weekly, or as prescribed.',
      sideEffects: ['Rare at recommended doses'],
      storageInstructions: 'Store below 30°C in a dry place.',
      manufacturerId: mankind._id,
      categoryId: otc._id,
      categoryGroup: 'healthcare',
      medicineType: 'other',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 40,
      sellingPrice: 32,
      gstPercentage: 12,
      hsnCode: '30045090',
      packSize: '1 sachet',
      images: [IMG_TABLETS_3],
      tags: ['vitamin', 'bone health'],
      isActive: true,
      stock: 400,
    },
    {
      name: 'Vitamin B Complex Tablet',
      slug: 'vitamin-b-complex-tablet',
      shortDescription: 'Daily B-vitamin supplement for energy',
      description: 'Vitamin B Complex supports energy metabolism, nerve function, and overall wellbeing.',
      composition: ['Vitamin B1', 'Vitamin B6', 'Vitamin B12', 'Folic Acid'],
      uses: ['Nutritional supplementation', 'Energy support'],
      dosage: 'One tablet daily after meals.',
      sideEffects: ['Mild stomach upset'],
      storageInstructions: 'Store below 30°C.',
      manufacturerId: himalaya._id,
      categoryId: otc._id,
      categoryGroup: 'healthcare',
      medicineType: 'tablet',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 110,
      sellingPrice: 85,
      gstPercentage: 12,
      hsnCode: '30045090',
      packSize: '30 tablets',
      images: [IMG_TABLETS_1],
      tags: ['vitamin', 'energy'],
      isActive: true,
      stock: 350,
    },
    {
      name: 'Calcium + Vitamin D3 Tablet',
      slug: 'calcium-vitamin-d3-tablet',
      shortDescription: 'Supports strong bones and teeth',
      description: 'Calcium with Vitamin D3 supports bone density, teeth health, and muscle function.',
      composition: ['Calcium Carbonate 500mg', 'Vitamin D3 250IU'],
      uses: ['Bone health', 'Calcium deficiency'],
      dosage: 'One tablet twice daily after meals, or as prescribed.',
      sideEffects: ['Constipation (rare)'],
      storageInstructions: 'Store below 30°C in a dry place.',
      manufacturerId: gsk._id,
      categoryId: otc._id,
      categoryGroup: 'healthcare',
      medicineType: 'tablet',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 145,
      sellingPrice: 112,
      gstPercentage: 12,
      hsnCode: '30045090',
      packSize: '15 tablets',
      images: [IMG_TABLETS_2],
      tags: ['vitamin', 'bone health', 'calcium'],
      isActive: true,
      stock: 300,
    },
    {
      name: 'Multivitamin Tablet',
      slug: 'multivitamin-tablet',
      shortDescription: 'Complete daily multivitamin and mineral support',
      description: 'A comprehensive multivitamin and multimineral formula for daily nutritional support.',
      composition: ['Multivitamins', 'Multiminerals', 'Antioxidants'],
      uses: ['General wellness', 'Nutritional gaps'],
      dosage: 'One tablet daily after breakfast.',
      sideEffects: ['Mild stomach upset'],
      storageInstructions: 'Store below 30°C.',
      manufacturerId: abbott._id,
      categoryId: otc._id,
      categoryGroup: 'healthcare',
      medicineType: 'tablet',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 180,
      sellingPrice: 139,
      gstPercentage: 12,
      hsnCode: '30045090',
      packSize: '30 tablets',
      images: [IMG_TABLETS_3],
      tags: ['vitamin', 'multivitamin'],
      isActive: true,
      stock: 280,
    },
    {
      name: 'Iron + Folic Acid Tablet',
      slug: 'iron-folic-acid-tablet',
      shortDescription: 'Supports healthy blood and prevents anemia',
      description: 'Iron with Folic Acid supports red blood cell production and helps prevent iron-deficiency anemia.',
      composition: ['Ferrous Ascorbate 100mg', 'Folic Acid 1.5mg'],
      uses: ['Anemia prevention', 'Iron deficiency'],
      dosage: 'One tablet daily after meals, or as prescribed.',
      sideEffects: ['Constipation', 'Dark stools'],
      storageInstructions: 'Store below 30°C in a dry place.',
      manufacturerId: zydus._id,
      categoryId: otc._id,
      categoryGroup: 'healthcare',
      medicineType: 'tablet',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 95,
      sellingPrice: 74,
      gstPercentage: 12,
      hsnCode: '30045090',
      packSize: '15 tablets',
      images: [IMG_TABLETS_1],
      tags: ['vitamin', 'anemia', 'iron'],
      isActive: true,
      stock: 260,
    },
    {
      name: 'Omega-3 Fish Oil Capsule',
      slug: 'omega-3-fish-oil-capsule',
      shortDescription: 'Supports heart and brain health',
      description: 'Omega-3 Fish Oil capsules provide essential fatty acids that support cardiovascular and cognitive health.',
      composition: ['EPA 180mg', 'DHA 120mg'],
      uses: ['Heart health', 'Brain health'],
      dosage: 'One capsule daily after meals.',
      sideEffects: ['Mild fishy aftertaste'],
      storageInstructions: 'Store below 30°C, away from sunlight.',
      manufacturerId: himalaya._id,
      categoryId: otc._id,
      categoryGroup: 'healthcare',
      medicineType: 'capsule',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 320,
      sellingPrice: 249,
      gstPercentage: 12,
      hsnCode: '30045090',
      packSize: '30 capsules',
      images: [IMG_CAPSULES_1],
      tags: ['vitamin', 'omega-3', 'heart health'],
      isActive: true,
      stock: 200,
    },
    {
      name: 'Zinc Tablet',
      slug: 'zinc-tablet',
      shortDescription: 'Supports immunity and skin health',
      description: 'Zinc supplement tablets support immune function, wound healing, and skin health.',
      composition: ['Zinc Sulphate 50mg'],
      uses: ['Immunity support', 'Skin health'],
      dosage: 'One tablet daily after meals.',
      sideEffects: ['Mild nausea at high doses'],
      storageInstructions: 'Store below 30°C.',
      manufacturerId: alkem._id,
      categoryId: otc._id,
      categoryGroup: 'healthcare',
      medicineType: 'tablet',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 85,
      sellingPrice: 66,
      gstPercentage: 12,
      hsnCode: '30045090',
      packSize: '20 tablets',
      images: [IMG_TABLETS_2],
      tags: ['vitamin', 'immunity', 'zinc'],
      isActive: true,
      stock: 240,
    },

    // ---- Skin Care / Topical ----
    {
      name: 'Antiseptic Cream',
      slug: 'antiseptic-cream',
      shortDescription: 'First-aid antiseptic for cuts and wounds',
      description: 'A broad-spectrum antiseptic cream for minor cuts, wounds, and skin infections.',
      composition: ['Cetrimide 0.5%', 'Chlorhexidine 0.1%'],
      uses: ['Minor cuts', 'Wound care', 'Skin infections'],
      dosage: 'Apply a thin layer on the affected area 2-3 times daily.',
      sideEffects: ['Mild skin irritation (rare)'],
      storageInstructions: 'Store below 30°C.',
      manufacturerId: jnj._id,
      categoryId: otc._id,
      categoryGroup: 'healthcare',
      medicineType: 'ointment',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 65,
      sellingPrice: 51,
      gstPercentage: 18,
      hsnCode: '30049099',
      packSize: '20g',
      images: [IMG_CREAM],
      tags: ['first aid', 'antiseptic'],
      isActive: true,
      stock: 220,
    },
    {
      name: 'Clotrimazole Antifungal Cream',
      slug: 'clotrimazole-antifungal-cream',
      shortDescription: 'Effective treatment for fungal skin infections',
      description: 'Clotrimazole cream treats fungal infections such as ringworm, athlete’s foot, and yeast infections.',
      composition: ['Clotrimazole 1%'],
      uses: ['Fungal infections', 'Ringworm', "Athlete's foot"],
      dosage: 'Apply twice daily to the affected area for 2-4 weeks.',
      sideEffects: ['Mild burning sensation'],
      storageInstructions: 'Store below 30°C.',
      manufacturerId: glenmark._id,
      categoryId: otc._id,
      categoryGroup: 'medicine',
      medicineType: 'ointment',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 55,
      sellingPrice: 43,
      gstPercentage: 18,
      hsnCode: '30049099',
      packSize: '20g',
      images: [IMG_CREAM],
      tags: ['skin', 'antifungal'],
      isActive: true,
      stock: 200,
    },
    {
      name: 'Calamine Lotion',
      slug: 'calamine-lotion',
      shortDescription: 'Soothing relief from itching and skin irritation',
      description: 'Calamine lotion soothes skin irritation, itching, and minor rashes including chickenpox and insect bites.',
      composition: ['Calamine 8%', 'Zinc Oxide 8%'],
      uses: ['Itching relief', 'Rashes', 'Insect bites'],
      dosage: 'Apply liberally to the affected area as needed.',
      sideEffects: [],
      storageInstructions: 'Store below 30°C, shake well before use.',
      manufacturerId: himalaya._id,
      categoryId: otc._id,
      categoryGroup: 'medicine',
      medicineType: 'other',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 75,
      sellingPrice: 58,
      gstPercentage: 18,
      hsnCode: '30049099',
      packSize: '120ml',
      images: [IMG_CREAM],
      tags: ['skin', 'itching'],
      isActive: true,
      stock: 180,
    },
    {
      name: 'Mupirocin Ointment',
      slug: 'mupirocin-ointment',
      shortDescription: 'Topical antibiotic for bacterial skin infections',
      description: 'Mupirocin ointment treats bacterial skin infections such as impetigo and infected wounds.',
      composition: ['Mupirocin 2%'],
      uses: ['Bacterial skin infections', 'Impetigo'],
      dosage: 'Apply a small amount 3 times daily for 5-10 days, or as prescribed.',
      sideEffects: ['Burning', 'Itching at application site'],
      storageInstructions: 'Store below 25°C.',
      manufacturerId: gsk._id,
      categoryId: rx._id,
      categoryGroup: 'medicine',
      medicineType: 'ointment',
      scheduleClass: 'schedule_h',
      prescriptionRequired: true,
      mrp: 95,
      sellingPrice: 76,
      gstPercentage: 18,
      hsnCode: '30049099',
      packSize: '5g',
      images: [IMG_CREAM],
      tags: ['skin', 'antibiotic'],
      isActive: true,
      stock: 140,
    },

    // ---- Healthcare Devices ----
    {
      name: 'Digital Blood Pressure Monitor',
      slug: 'digital-blood-pressure-monitor',
      shortDescription: 'Accurate at-home blood pressure monitoring',
      description: 'A fully automatic digital BP monitor for accurate, easy at-home blood pressure tracking.',
      composition: ['N/A'],
      uses: ['Blood pressure monitoring'],
      sideEffects: [],
      storageInstructions: 'Store in a dry place at room temperature.',
      manufacturerId: abbott._id,
      categoryId: devices._id,
      categoryGroup: 'devices',
      medicineType: 'device',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 2499,
      sellingPrice: 1799,
      gstPercentage: 18,
      hsnCode: '90189099',
      packSize: '1 unit',
      images: [IMG_DEVICE],
      tags: ['bp monitor', 'device'],
      isActive: true,
      stock: 60,
    },
    {
      name: 'Blood Glucose Monitor (Glucometer)',
      slug: 'blood-glucose-monitor-glucometer',
      shortDescription: 'Quick and accurate blood sugar testing at home',
      description: 'A reliable glucometer kit for at-home blood sugar monitoring, includes lancing device.',
      composition: ['N/A'],
      uses: ['Blood sugar monitoring'],
      sideEffects: [],
      storageInstructions: 'Store in a dry place, avoid extreme temperatures.',
      manufacturerId: abbott._id,
      categoryId: devices._id,
      categoryGroup: 'devices',
      medicineType: 'device',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 1299,
      sellingPrice: 899,
      gstPercentage: 18,
      hsnCode: '90278090',
      packSize: '1 unit + 10 strips',
      images: [IMG_DEVICE],
      tags: ['glucometer', 'diabetes', 'device'],
      isActive: true,
      stock: 70,
    },
    {
      name: 'Glucometer Test Strips (Pack of 50)',
      slug: 'glucometer-test-strips-50',
      shortDescription: 'Compatible test strips for blood glucose monitors',
      description: 'A pack of 50 test strips for accurate blood glucose readings, compatible with standard glucometers.',
      composition: ['N/A'],
      uses: ['Blood sugar monitoring'],
      sideEffects: [],
      storageInstructions: 'Store in a cool, dry place, keep vial tightly closed.',
      manufacturerId: abbott._id,
      categoryId: devices._id,
      categoryGroup: 'devices',
      medicineType: 'device',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 650,
      sellingPrice: 499,
      gstPercentage: 18,
      hsnCode: '38220090',
      packSize: '50 strips',
      images: [IMG_DEVICE],
      tags: ['glucometer', 'diabetes', 'device'],
      isActive: true,
      stock: 150,
    },
    {
      name: 'Pulse Oximeter',
      slug: 'pulse-oximeter',
      shortDescription: 'Monitor blood oxygen levels and pulse rate',
      description: 'A fingertip pulse oximeter for quick measurement of blood oxygen saturation (SpO2) and pulse rate.',
      composition: ['N/A'],
      uses: ['Oxygen saturation monitoring', 'Pulse rate monitoring'],
      sideEffects: [],
      storageInstructions: 'Store in a dry place at room temperature.',
      manufacturerId: jnj._id,
      categoryId: devices._id,
      categoryGroup: 'devices',
      medicineType: 'device',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 1999,
      sellingPrice: 1299,
      gstPercentage: 18,
      hsnCode: '90189099',
      packSize: '1 unit',
      images: [IMG_DEVICE],
      tags: ['oximeter', 'device'],
      isActive: true,
      stock: 90,
    },
    {
      name: 'Compressor Nebulizer',
      slug: 'compressor-nebulizer',
      shortDescription: 'At-home respiratory therapy device',
      description: 'A compressor nebulizer for delivering medication directly to the lungs, ideal for asthma and respiratory conditions.',
      composition: ['N/A'],
      uses: ['Respiratory therapy', 'Asthma management'],
      sideEffects: [],
      storageInstructions: 'Store in a dry place, clean mask and tubing after each use.',
      manufacturerId: jnj._id,
      categoryId: devices._id,
      categoryGroup: 'devices',
      medicineType: 'device',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 2999,
      sellingPrice: 2199,
      gstPercentage: 18,
      hsnCode: '90189099',
      packSize: '1 unit',
      images: [IMG_DEVICE],
      tags: ['nebulizer', 'respiratory', 'device'],
      isActive: true,
      stock: 40,
    },
    {
      name: 'N95 Face Mask (Pack of 5)',
      slug: 'n95-face-mask-pack-5',
      shortDescription: 'High-filtration protective face masks',
      description: 'N95-rated face masks offering high-filtration protection for everyday use, pack of 5.',
      composition: ['N/A'],
      uses: ['Respiratory protection'],
      sideEffects: [],
      storageInstructions: 'Store in a clean, dry place.',
      manufacturerId: reckitt._id,
      categoryId: devices._id,
      categoryGroup: 'devices',
      medicineType: 'device',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 250,
      sellingPrice: 199,
      gstPercentage: 12,
      hsnCode: '63079090',
      packSize: '5 masks',
      images: [IMG_PERSONAL],
      tags: ['mask', 'protection'],
      isActive: true,
      stock: 300,
    },
    {
      name: 'Hot Water Bag',
      slug: 'hot-water-bag',
      shortDescription: 'Soothing heat therapy for aches and cramps',
      description: 'A durable rubber hot water bag for soothing relief from muscle aches, cramps, and cold-weather comfort.',
      composition: ['N/A'],
      uses: ['Pain relief', 'Muscle relaxation'],
      sideEffects: [],
      storageInstructions: 'Store dry and empty when not in use.',
      manufacturerId: himalaya._id,
      categoryId: devices._id,
      categoryGroup: 'devices',
      medicineType: 'device',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 299,
      sellingPrice: 229,
      gstPercentage: 18,
      hsnCode: '40140090',
      packSize: '1 unit',
      images: [IMG_DEVICE],
      tags: ['pain relief', 'device'],
      isActive: true,
      stock: 100,
    },
    {
      name: 'Knee Cap Support (Pair)',
      slug: 'knee-cap-support-pair',
      shortDescription: 'Compression support for knee pain and stability',
      description: 'Elastic knee cap support providing compression and stability for knee pain, sprains, and arthritis.',
      composition: ['N/A'],
      uses: ['Knee pain relief', 'Joint support'],
      sideEffects: [],
      storageInstructions: 'Hand wash and air dry.',
      manufacturerId: jnj._id,
      categoryId: devices._id,
      categoryGroup: 'devices',
      medicineType: 'device',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 450,
      sellingPrice: 349,
      gstPercentage: 12,
      hsnCode: '90211010',
      packSize: '1 pair',
      images: [IMG_DEVICE],
      tags: ['support', 'orthopedic', 'device'],
      isActive: true,
      stock: 80,
    },

    // ---- Baby Care ----
    {
      name: 'Baby Lotion',
      slug: 'baby-lotion',
      shortDescription: 'Gentle daily moisturizer for delicate baby skin',
      description: 'A mild, hypoallergenic lotion formulated to gently moisturize and protect delicate baby skin.',
      composition: ['N/A'],
      uses: ['Daily skin moisturizing'],
      dosage: 'Apply gently after bath time as needed.',
      sideEffects: [],
      storageInstructions: 'Store below 30°C, away from direct sunlight.',
      manufacturerId: jnj._id,
      categoryId: babyCare._id,
      categoryGroup: 'baby_care',
      medicineType: 'other',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 180,
      sellingPrice: 144,
      gstPercentage: 18,
      hsnCode: '33049990',
      packSize: '200ml',
      images: [IMG_CREAM],
      tags: ['baby care', 'skin'],
      isActive: true,
      stock: 220,
    },
    {
      name: 'Baby Powder',
      slug: 'baby-powder',
      shortDescription: 'Soft and gentle talc for baby skin',
      description: 'A gentle, dermatologist-tested baby powder that helps keep skin soft, dry, and comfortable.',
      composition: ['N/A'],
      uses: ['Skin dryness', 'Chafing prevention'],
      dosage: 'Apply lightly after bath, avoid the face.',
      sideEffects: [],
      storageInstructions: 'Store in a dry place, keep container closed.',
      manufacturerId: jnj._id,
      categoryId: babyCare._id,
      categoryGroup: 'baby_care',
      medicineType: 'other',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 150,
      sellingPrice: 119,
      gstPercentage: 18,
      hsnCode: '33049990',
      packSize: '200g',
      images: [IMG_CREAM],
      tags: ['baby care'],
      isActive: true,
      stock: 250,
    },
    {
      name: 'Baby Shampoo',
      slug: 'baby-shampoo',
      shortDescription: 'No-tears formula for gentle hair wash',
      description: 'A tear-free, mild shampoo specially formulated for a baby’s delicate scalp and hair.',
      composition: ['N/A'],
      uses: ['Hair and scalp cleansing'],
      dosage: 'Use during bath time, rinse thoroughly.',
      sideEffects: [],
      storageInstructions: 'Store below 30°C.',
      manufacturerId: jnj._id,
      categoryId: babyCare._id,
      categoryGroup: 'baby_care',
      medicineType: 'other',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 165,
      sellingPrice: 132,
      gstPercentage: 18,
      hsnCode: '33051090',
      packSize: '200ml',
      images: [IMG_PERSONAL],
      tags: ['baby care'],
      isActive: true,
      stock: 200,
    },
    {
      name: 'Baby Wipes (Pack of 80)',
      slug: 'baby-wipes-pack-80',
      shortDescription: 'Soft, gentle wipes for everyday cleaning',
      description: 'Soft, alcohol-free baby wipes for gentle everyday cleaning of skin during diaper changes.',
      composition: ['N/A'],
      uses: ['Skin cleaning', 'Diaper changes'],
      dosage: 'Use as needed during diaper changes and cleanups.',
      sideEffects: [],
      storageInstructions: 'Keep pack sealed to retain moisture.',
      manufacturerId: jnj._id,
      categoryId: babyCare._id,
      categoryGroup: 'baby_care',
      medicineType: 'other',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 199,
      sellingPrice: 159,
      gstPercentage: 18,
      hsnCode: '96190090',
      packSize: '80 wipes',
      images: [IMG_PERSONAL],
      tags: ['baby care'],
      isActive: true,
      stock: 280,
    },
    {
      name: 'Gripe Water',
      slug: 'gripe-water',
      shortDescription: 'Traditional relief from infant colic and gas',
      description: 'A gentle, traditional formula that helps relieve colic, gas, and hiccups in infants.',
      composition: ['Dill Oil', 'Sodium Bicarbonate'],
      uses: ['Colic relief', 'Gas relief'],
      dosage: 'As directed by your pediatrician based on age.',
      sideEffects: [],
      storageInstructions: 'Store below 30°C, shake well before use.',
      manufacturerId: himalaya._id,
      categoryId: babyCare._id,
      categoryGroup: 'baby_care',
      medicineType: 'syrup',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 95,
      sellingPrice: 76,
      gstPercentage: 12,
      hsnCode: '30049011',
      packSize: '130ml',
      images: [IMG_BLISTER],
      tags: ['baby care', 'colic'],
      isActive: true,
      stock: 180,
    },
    {
      name: 'Baby Diapers (Medium, Pack of 36)',
      slug: 'baby-diapers-medium-36',
      shortDescription: 'Soft, absorbent diapers for all-day comfort',
      description: 'Ultra-absorbent, soft diapers that keep your baby dry and comfortable for up to 12 hours.',
      composition: ['N/A'],
      uses: ['Diapering'],
      dosage: 'Change every 3-4 hours or as needed.',
      sideEffects: [],
      storageInstructions: 'Store in a dry place.',
      manufacturerId: jnj._id,
      categoryId: babyCare._id,
      categoryGroup: 'baby_care',
      medicineType: 'other',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 549,
      sellingPrice: 449,
      gstPercentage: 18,
      hsnCode: '96190010',
      packSize: '36 diapers',
      images: [IMG_PERSONAL],
      tags: ['baby care', 'diapers'],
      isActive: true,
      stock: 150,
    },

    // ---- Personal Care ----
    {
      name: 'Hand Sanitizer 500ml',
      slug: 'hand-sanitizer-500ml',
      shortDescription: '70% alcohol-based protection on the go',
      description: 'A 70% alcohol-based hand sanitizer that kills 99.9% of germs without water.',
      composition: ['Ethyl Alcohol 70% v/v'],
      uses: ['Hand hygiene'],
      dosage: 'Apply a small amount and rub hands until dry.',
      sideEffects: ['Skin dryness with frequent use'],
      storageInstructions: 'Store away from flame, keep cap tightly closed.',
      manufacturerId: reckitt._id,
      categoryId: personalCare._id,
      categoryGroup: 'personal_care',
      medicineType: 'other',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 150,
      sellingPrice: 119,
      gstPercentage: 18,
      hsnCode: '38089400',
      packSize: '500ml',
      images: [IMG_PERSONAL],
      tags: ['hygiene', 'sanitizer'],
      isActive: true,
      stock: 350,
    },
    {
      name: 'Antibacterial Soap',
      slug: 'antibacterial-soap',
      shortDescription: 'Daily protection against germs',
      description: 'An antibacterial bathing soap that cleanses and protects skin from germs.',
      composition: ['N/A'],
      uses: ['Hand and body hygiene'],
      dosage: 'Use during bath or handwashing.',
      sideEffects: [],
      storageInstructions: 'Store in a dry place.',
      manufacturerId: reckitt._id,
      categoryId: personalCare._id,
      categoryGroup: 'personal_care',
      medicineType: 'other',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 45,
      sellingPrice: 36,
      gstPercentage: 18,
      hsnCode: '34013000',
      packSize: '125g',
      images: [IMG_PERSONAL],
      tags: ['hygiene', 'soap'],
      isActive: true,
      stock: 400,
    },
    {
      name: 'Sensitive Toothpaste',
      slug: 'sensitive-toothpaste',
      shortDescription: 'Relief from sensitive teeth, day and night',
      description: 'A specially formulated toothpaste that provides long-lasting relief from tooth sensitivity.',
      composition: ['Potassium Nitrate', 'Sodium Fluoride'],
      uses: ['Tooth sensitivity relief', 'Oral hygiene'],
      dosage: 'Brush twice daily.',
      sideEffects: [],
      storageInstructions: 'Store below 30°C.',
      manufacturerId: gsk._id,
      categoryId: personalCare._id,
      categoryGroup: 'personal_care',
      medicineType: 'other',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 110,
      sellingPrice: 89,
      gstPercentage: 18,
      hsnCode: '33061010',
      packSize: '100g',
      images: [IMG_PERSONAL],
      tags: ['oral care', 'toothpaste'],
      isActive: true,
      stock: 300,
    },
    {
      name: 'Sanitary Pads (Pack of 30)',
      slug: 'sanitary-pads-pack-30',
      shortDescription: 'Reliable all-day protection and comfort',
      description: 'Ultra-thin sanitary pads with high absorbency for reliable, comfortable all-day protection.',
      composition: ['N/A'],
      uses: ['Menstrual hygiene'],
      dosage: 'Change every 4-6 hours as needed.',
      sideEffects: [],
      storageInstructions: 'Store in a dry place.',
      manufacturerId: reckitt._id,
      categoryId: personalCare._id,
      categoryGroup: 'personal_care',
      medicineType: 'other',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 220,
      sellingPrice: 175,
      gstPercentage: 12,
      hsnCode: '96190040',
      packSize: '30 pads',
      images: [IMG_PERSONAL],
      tags: ['hygiene', 'feminine care'],
      isActive: true,
      stock: 260,
    },
    {
      name: 'Moisturizing Body Lotion',
      slug: 'moisturizing-body-lotion',
      shortDescription: '24-hour hydration for soft, healthy skin',
      description: 'A nourishing body lotion that provides 24-hour hydration for soft, smooth, healthy-looking skin.',
      composition: ['N/A'],
      uses: ['Skin moisturizing'],
      dosage: 'Apply daily after bathing.',
      sideEffects: [],
      storageInstructions: 'Store below 30°C, away from direct sunlight.',
      manufacturerId: himalaya._id,
      categoryId: personalCare._id,
      categoryGroup: 'personal_care',
      medicineType: 'other',
      scheduleClass: 'none',
      prescriptionRequired: false,
      mrp: 195,
      sellingPrice: 154,
      gstPercentage: 18,
      hsnCode: '33049990',
      packSize: '200ml',
      images: [IMG_CREAM],
      tags: ['skin care', 'moisturizer'],
      isActive: true,
      stock: 240,
    },
  ];

  for (const med of medicines) {
    const { stock, ...medData } = med;
    const existing = await MedicineModel.findOne({ slug: medData.slug });
    const created = existing ?? (await MedicineModel.create(medData as never));
    const medicine = Array.isArray(created) ? created[0]! : created;
    await InventoryModel.findOneAndUpdate(
      { medicineId: medicine._id, branchId: branch._id },
      { $set: { totalQuantity: stock }, $setOnInsert: { reservedQuantity: 0 } },
      { upsert: true },
    );
    logger.info(`Seeded: ${medicine.name}`);
  }

  await disconnectDatabase();
  logger.info('Demo medicines seeded.');
}

main().catch((err) => {
  logger.error({ err }, 'Demo data seed failed');
  process.exit(1);
});
